spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #defer-datasource-initialization: true
    properties:
      hibernate:
        # ddl-auto: utilizado para rodar a aplicação após o uso de migrations
        ddl-auto: create
        show_sql: true
        format_sql: true

    # Código abaixo utilizado para rodar a aplicação após o uso de migrations
    flyway.locations.filesystem: db/migration
    # O código abaixo habilita o código do h2
    h2:
      console:
        enabled: true

